name: Wyam

on:
  push:
    branches:
    - wyam  # default branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.802
    - name: Install Wyam
      run: |
        export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
        dotnet tool install --tool-path . wyam.tool
    - name: Publish blog
      run: |
        ./wyam -r blog -t CleanBlog
        cp CNAME output
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        PUBLISH_BRANCH: main  # deploying branch
        PUBLISH_DIR: ./output